In [60]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt     
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

data = pd.read_csv('../data/Students Social Media Addiction.csv')
data["Avg_Daily_Usage_Hours_cat"] = pd.cut(data["Avg_Daily_Usage_Hours"], bins=[0, 3, 5, 7, np.inf], labels=[1, 2, 3, 4])
# data["Avg_Daily_Usage_Hours_cat"].hist()

In [ ]:
from sklearn.model_selection import StratifiedShuffleSplit

# Stratified Split
stratified_split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=3)
for train_index, test_index in stratified_split.split(data, data["Avg_Daily_Usage_Hours_cat"]):
    strat_train_set = data.loc[train_index]
    strat_test_set = data.loc[test_index]

# Random Split
random_split = data["Avg_Daily_Usage_Hours_cat"].sample(frac=0.8, random_state=3)


random_set_ratio = random_split.value_counts() / len(random_split)
strat_set_ratio = strat_train_set["Avg_Daily_Usage_Hours_cat"].value_counts() / len(strat_train_set["Avg_Daily_Usage_Hours_cat"])


print(len(strat_train_set["Avg_Daily_Usage_Hours_cat"]))
print(len(data["Avg_Daily_Usage_Hours"]))

564
705

In [67]:
data.head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score,Avg_Daily_Usage_Hours_cat
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8,3
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3,1
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9,3
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4,1
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7,2

In [72]:
data.drop("Avg_Daily_Usage_Hours_cat", axis=1, inplace=True)

KeyError: "['Avg_Daily_Usage_Hours_cat'] not found in axis"